const $=id=>document.getElementById(id);
const state={page:1,pageSize:10,total:0,search:"",section:"",students:[]};
const esc=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
async function request(url,options={}){const response=await fetch(url,options);if(response.status===204)return null;const data=await response.json();if(!response.ok){const detail=data.detail;throw new Error(Array.isArray(detail)?detail.map(x=>x.msg).join(" "):detail||"No se pudo completar la operación.");}return data;}
function feedback(message,error=false){$("feedback").textContent=message;$("feedback").classList.toggle("error",error);$("feedback").classList.remove("hidden");clearTimeout(feedback.timer);feedback.timer=setTimeout(()=>$("feedback").classList.add("hidden"),5500);}
function changeView(name){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`${name}View`));document.querySelectorAll(".nav-link").forEach(v=>v.classList.toggle("active",v.dataset.view===name));$("currentSection").textContent=({dashboard:"Dashboard",students:"Estudiantes",reports:"Reportes"})[name];document.querySelector(".sidebar").classList.remove("open");if(name==="reports")loadReports();}
document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>changeView(b.dataset.view)));document.querySelectorAll("[data-go]").forEach(b=>b.addEventListener("click",()=>changeView(b.dataset.go)));$("menuButton").addEventListener("click",()=>document.querySelector(".sidebar").classList.toggle("open"));
const badge=s=>`<span class="badge ${s.academic_status}">${s.academic_status==="passing"?"Aprobado":"En riesgo"}</span>`;
function row(s,actions=true){const initials=s.full_name.split(" ").slice(0,2).map(w=>w[0]).join("").toUpperCase();return `<tr><td><div class="student-cell"><span class="avatar">${esc(initials)}</span><strong>${esc(s.full_name)}</strong></div></td><td>${esc(s.section)}</td>${actions?`<td>${s.spanish_grade}</td><td>${s.english_grade}</td><td>${s.social_studies_grade}</td><td>${s.science_grade}</td>`:""}<td><strong>${s.average}</strong></td><td>${badge(s)}</td>${actions?`<td><div class="actions"><button class="action-button" data-edit="${s.id}">Editar</button><button class="action-button delete" data-delete="${s.id}">Eliminar</button></div></td>`:""}</tr>`;}
async function loadDashboard(){try{const [summary,recent]=await Promise.all([request("/api/v1/dashboard"),request("/api/v1/students?page=1&page_size=5")]);$("totalStudents").textContent=summary.total_students;$("generalAverage").textContent=Number(summary.general_average).toFixed(2);$("passingStudents").textContent=summary.passing_students;$("atRiskStudents").textContent=summary.students_at_risk;const max=Math.max(...summary.sections.map(x=>x.total),1);$("sectionChart").innerHTML=summary.sections.length?summary.sections.map(x=>`<div class="chart-column"><strong>${x.total}</strong><span class="chart-bar" style="height:${Math.max(8,x.total/max*150)}px"></span><small>${esc(x.section)}</small></div>`).join(""):'<div class="empty-state">Aún no hay secciones registradas.</div>';const pct=summary.passing_students/(summary.total_students||1)*100;$("statusDonut").innerHTML=`<div class="donut" style="background:conic-gradient(#22a777 0 ${pct}%,#f0a43a ${pct}% 100%)"><div class="donut-center"><strong>${summary.total_students}</strong><small>estudiantes</small></div></div>`;$("recentStudents").innerHTML=recent.items.length?recent.items.map(s=>row(s,false)).join(""):'<tr><td colspan="4" class="empty-state">Aún no hay estudiantes.</td></tr>';const current=$("sectionFilter").value;$("sectionFilter").innerHTML='<option value="">Todas las secciones</option>'+summary.sections.map(x=>`<option>${esc(x.section)}</option>`).join("");$("sectionFilter").value=current;}catch(e){feedback(e.message,true);}}
async function loadStudents(){const p=new URLSearchParams({page:state.page,page_size:state.pageSize});if(state.search)p.set("search",state.search);if(state.section)p.set("section",state.section);try{const data=await request(`/api/v1/students?${p}`);state.students=data.items;state.total=data.total;$("studentRows").innerHTML=data.items.length?data.items.map(s=>row(s)).join(""):'<tr><td colspan="9" class="empty-state">No se encontraron estudiantes.</td></tr>';const pages=Math.max(1,Math.ceil(data.total/state.pageSize));$("pageInfo").textContent=`Página ${state.page} de ${pages} · ${data.total} registros`;$("previousPage").disabled=state.page<=1;$("nextPage").disabled=state.page>=pages;}catch(e){feedback(e.message,true);}}
function openForm(s=null){$("studentFormPanel").classList.remove("hidden");$("formTitle").textContent=s?"Editar estudiante":"Nuevo estudiante";$("studentId").value=s?.id||"";$("fullName").value=s?.full_name||"";$("section").value=s?.section||"";$("spanishGrade").value=s?.spanish_grade??"";$("englishGrade").value=s?.english_grade??"";$("socialGrade").value=s?.social_studies_grade??"";$("scienceGrade").value=s?.science_grade??"";$("studentFormPanel").scrollIntoView({behavior:"smooth"});}
function closeForm(){$("studentFormPanel").classList.add("hidden");$("studentForm").reset();}
$("studentRows").addEventListener("click",async e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete;if(edit)openForm(state.students.find(s=>s.id===edit));if(del&&confirm("¿Deseas eliminar este expediente? Esta acción no se puede deshacer.")){try{await request(`/api/v1/students/${del}`,{method:"DELETE"});feedback("Estudiante eliminado correctamente.");await refresh();}catch(error){feedback(error.message,true);}}});
$("studentForm").addEventListener("submit",async e=>{e.preventDefault();const id=$("studentId").value,payload={full_name:$("fullName").value,section:$("section").value,spanish_grade:Number($("spanishGrade").value),english_grade:Number($("englishGrade").value),social_studies_grade:Number($("socialGrade").value),science_grade:Number($("scienceGrade").value)};try{await request(id?`/api/v1/students/${id}`:"/api/v1/students",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});closeForm();feedback(id?"Estudiante actualizado correctamente.":"Estudiante registrado correctamente.");await refresh();}catch(error){feedback(error.message,true);}});
$("csvFile").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;const form=new FormData();form.append("file",file);try{const result=await request("/api/v1/students/import",{method:"POST",body:form});feedback(result.message+(result.errors.length?` ${result.errors.length} filas con error.`:""));await refresh();}catch(error){feedback(error.message,true);}e.target.value="";});
async function loadReports(){try{const [top,failed]=await Promise.all([request("/api/v1/students/top"),request("/api/v1/students/failed")]);$("topStudents").innerHTML=top.length?top.map((s,i)=>`<div class="rank-item"><span class="rank">${i+1}</span><div><strong>${esc(s.full_name)}</strong><small>Sección ${esc(s.section)}</small></div><b>${s.average}</b></div>`).join(""):'<div class="empty-state">No hay datos suficientes.</div>';$("failedStudents").innerHTML=failed.length?failed.map(s=>`<div class="risk-item"><div><strong>${esc(s.full_name)}</strong><small>${esc(s.section)} · Promedio ${s.average}</small></div><div class="subject-tags">${s.failed_subjects.map(x=>`<span>${esc(x.subject)}: ${x.score}</span>`).join("")}</div></div>`).join(""):'<div class="empty-state">No hay materias reprobadas.</div>';}catch(e){feedback(e.message,true);}}
async function refresh(){await Promise.all([loadDashboard(),loadStudents()]);}
$("newStudentButton").addEventListener("click",()=>openForm());["closeFormButton","cancelButton"].forEach(id=>$(id).addEventListener("click",closeForm));let timer;$("searchInput").addEventListener("input",e=>{clearTimeout(timer);timer=setTimeout(()=>{state.search=e.target.value.trim();state.page=1;loadStudents();},300);});$("sectionFilter").addEventListener("change",e=>{state.section=e.target.value;state.page=1;loadStudents();});$("previousPage").addEventListener("click",()=>{if(state.page>1){state.page--;loadStudents();}});$("nextPage").addEventListener("click",()=>{if(state.page*state.pageSize<state.total){state.page++;loadStudents();}});refresh();
